[audio]
enable_overdrive = true

[bar.default]
background_opacity = 0.89999997615814209
capsule = true
end = [ "notifications", "network", "bluetooth", "cpu", "ram", "temp", "volume", "brightness", "battery" ]
position = "bottom"
start = [ "launcher", "wallpaper", "workspaces", "tray", "media", "audio_visualizer" ]
widget_spacing = 5
margin_h = 0
margin_v = 0
radius = 0
scale = 0.94999998807907104
shadow = false
thickness = 25

[dock]
auto_hide = true
background_opacity = 0.89999997615814209
enabled = false
position = "top"

[notification]
background_opacity = 0.89999997615814209

[shell]
avatar_path = "/home/sunny/arch-files/haruta.jpg"
clipboard_auto_paste = "off"
password_style = "random"
polkit_agent = true
telemetry_enabled = false

[theme]
builtin = "Noctalia"
source = "wallpaper"
wallpaper_scheme = "faithful"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "helix", "kcolorscheme", "niri", "kitty" ]
    enable_user_templates = true

[wallpaper]
directory = "/home/sunny/Pictures/walls"

[weather]
address = "Jatani, India"

[widget.clock]
format = "{:%a, %b %d, %H:%M}"

[widget.workspaces]
display = "none"

[widget.cpu]
display = "gauge"
show_label = false
type = "sysmon"

[widget.ram]
display = "gauge"
show_label = false
stat = "ram_used"
type = "sysmon"

[widget.temp]
show_label = false
stat = "cpu_temp"
type = "sysmon"
