[config]

[templates]

[templates.vesktop]
input_path = "~/.config/noctalia/themes/discord-material.css"
output_path = "~/.config/vesktop/themes/noctalia-material.theme.css"

[templates.pywalfox]
input_path = "~/.config/noctalia/themes/pywalfox.json"
output_path = "~/.cache/wal/colors.json"
post_hook = "pywalfox update"
