title	Arch Linux (linux-cachyos)
linux	/vmlinuz-linux-cachyos
initrd	/intel-ucode.img
initrd	/initramfs-linux-cachyos.img
options root=LABEL=root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs
