[[mgr.prepend_keymap]]
desc = "sudo paste"
on = ["R", "p", "p"]
run = "plugin sudo -- paste"

[[mgr.prepend_keymap]]
desc = "sudo paste force"
on = ["R", "P"]
run = "plugin sudo -- paste --force"

[[mgr.prepend_keymap]]
desc = "sudo rename"
on = ["R", "r"]
run = "plugin sudo -- rename"

[[mgr.prepend_keymap]]
desc = "sudo link"
on = ["R", "p", "l"]
run = "plugin sudo -- link"

[[mgr.prepend_keymap]]
desc = "sudo link relative path"
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"

[[mgr.prepend_keymap]]
desc = "sudo hardlink"
on = ["R", "p", "L"]
run = "plugin sudo -- hardlink"

[[mgr.prepend_keymap]]
desc = "sudo create"
on = ["R", "a"]
run = "plugin sudo -- create"

[[mgr.prepend_keymap]]
desc = "sudo trash"
on = ["R", "d"]
run = "plugin sudo -- remove"

[[mgr.prepend_keymap]]
desc = "sudo delete"
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"

[[mgr.prepend_keymap]]
desc = "sudo chmod"
on = ["R", "m"]
run = "plugin sudo -- chmod"

[[mgr.prepend_keymap]]
desc = "Select device then mount"
on = ["M", "m"]
run = "plugin gvfs -- select-then-mount"

[[mgr.prepend_keymap]]
desc = "Select device, mount, and jump"
on = ["M", "J"]
run = "plugin gvfs -- select-then-mount --jump"

[[mgr.prepend_keymap]]
desc = "Remount device under cwd"
on = ["M", "R"]
run = "plugin gvfs -- remount-current-cwd-device"

[[mgr.prepend_keymap]]
desc = "Select device then unmount"
on = ["M", "u"]
run = "plugin gvfs -- select-then-unmount"

[[mgr.prepend_keymap]]
desc = "Select device then eject"
on = ["M", "e"]
run = "plugin gvfs -- select-then-unmount --eject"

[[mgr.prepend_keymap]]
desc = "Force eject/unmount"
on = ["M", "E"]
run = "plugin gvfs -- select-then-unmount --eject --force"

[[mgr.prepend_keymap]]
desc = "Add a GVFS mount URI"
on = ["M", "a"]
run = "plugin gvfs -- add-mount"

[[mgr.prepend_keymap]]
desc = "Edit a GVFS mount URI"
on = ["M", "v", "e"]
run = "plugin gvfs -- edit-mount"

[[mgr.prepend_keymap]]
desc = "Remove a GVFS mount URI"
on = ["M", "v", "r"]
run = "plugin gvfs -- remove-mount"

[[mgr.prepend_keymap]]
desc = "Select device then jump to mount point"
on = ["g", "m"]
run = "plugin gvfs -- jump-to-device"

[[mgr.prepend_keymap]]
desc = "Automount then jump to mount point"
on = ["g", "M"]
run = "plugin gvfs -- jump-to-device --automount"

[[mgr.prepend_keymap]]
desc = "Jump back to previous position"
on = ["`", "`"]
run = "plugin gvfs -- jump-back-prev-cwd"

[[mgr.prepend_keymap]]
desc = "Enable automount on cd"
on = ["M", "t"]
run = "plugin gvfs -- automount-when-cd"

[[mgr.prepend_keymap]]
desc = "Disable automount on cd"
on = ["M", "T"]
run = "plugin gvfs -- automount-when-cd --disabled"

[[mgr.prepend_keymap]]
desc = "yafg"
on = ["F", "G"]
run = "plugin yafg"

[[mgr.prepend_keymap]]
desc = "Chmod on selected files"
on = ["c", "m"]
run = "plugin chmod"

[[mgr.prepend_keymap]]
desc = "Drag Files"
on = ["<C-d>"]
run = "plugin drag"

[[mgr.prepend_keymap]]
desc = "Yank selected files (copy)"
on = ["y"]
run = ["yank", "plugin clipboard -- --action=copy"]

[[mgr.prepend_keymap]]
desc = "Yank selected files (cut)"
on = ["x"]
run = ["yank --cut", "plugin clipboard -- --action=copy"]

[[mgr.prepend_keymap]]
desc = "Paste system clipboard files"
on = ["<C-p>"]
run = ["plugin clipboard -- --action=paste"]

[[mgr.prepend_keymap]]
desc = "Mount manager"
on = ["m"]
run = "plugin mount"
