[audio]
enable_overdrive = true

[osd]
background_opacity = 0.9

[bar.default]
background_opacity = 0.9
capsule = true
capsule_opacity = 0.9
capsule_radius = 8.0
end = [ "tray", "notifications", "group:g2", "group:g1", "group:g3" ]
position = "bottom"
start = [ "group:g5", "workspaces", "group:g4" ]
widget_spacing = 10
margin_edge = 0
margin_ends = 120
radius = 8
radius_bottom_left = 0
radius_bottom_right = 0
scale = 1.0
shadow = false
thickness = 30
attach_panels = true

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "ram", "temp" ]
    opacity = 0.9
    padding = 6.0
    radius = 8.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g2"
    members = [ "network", "bluetooth" ]
    opacity = 0.9
    padding = 6.0
    radius = 8.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g3"
    members = [ "volume", "brightness", "battery" ]
    opacity = 0.9
    padding = 6.0
    radius = 8.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g4"
    members = [ "media", "audio_visualizer" ]
    opacity = 0.9
    padding = 6.0
    radius = 8.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g5"
    members = [ "launcher", "screen_recorder", "wallpaper" ]
    opacity = 0.9
    padding = 6.0
    radius = 8.0

[idle]
behavior_order = [ "idle-behavior", "idle-behavior-2" ]

    [idle.behavior.idle-behavior]
    action = "lock"
    enabled = true
    timeout = 300

    [idle.behavior.idle-behavior-2]
    action = "screen_off"
    enabled = true
    timeout = 600

[location]
auto_locate = true

[dock]
auto_hide = true
background_opacity = 0.9
enabled = false
position = "top"

[notification]
background_opacity = 0.9

[shell]
avatar_path = "/home/sunny/.face"
clipboard_auto_paste = "off"
password_style = "random"
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = false
clipboard_image_action_command = "satty -f -"

    [shell.panel]
    transparency_mode = "glass"
    clipboard_placement = "attached"
    launcher_placement = "attached"
    attach_session = true

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "pkill noctalia && noctalia -d"
    enabled = true
    glyph = "noctalia"
    label = "Restart Noctalia"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    variant = "default"

[theme]
builtin = "Noctalia"
source = "wallpaper"
wallpaper_scheme = "faithful"
community_palette = "GruvboxAlt"

    [theme.templates]
    builtin_ids = [ "alacritty", "gtk3", "gtk4", "helix", "kcolorscheme", "niri" ]
    community_ids = [ "discord", "pywalfox" ]

[wallpaper]
directory = "/home/sunny/Pictures/walls"

    [widget.launcher]
    glyph = "niri"

    [widget.clock]
    format = "{:%a, %b %d, %H:%M}"

    [widget.network]
    show_label = false
    capsule_group = "wifi-bt"

    [widget.workspaces]
    display = "none"

    [widget.cpu]
    display = "gauge"
    show_label = false
    type = "sysmon"
    capsule_group = "sysmon"

    [widget.ram]
    display = "gauge"
    show_label = false
    stat = "ram_used"
    type = "sysmon"
    capsule_group = "sysmon"

    [widget.temp]
    show_label = false
    stat = "cpu_temp"
    type = "sysmon"
    capsule_group = "sysmon"

    [widget.audio_visualizer]
    capsule_group = "mpris"

    [widget.battery]
    capsule_group = "vol-bright-bat"

    [widget.bluetooth]
    capsule_group = "wifi-bt"

    [widget.brightness]
    capsule_group = "vol-bright-bat"
    show_label = false

    [widget.media]
    capsule_group = "mpris"

    [widget.volume]
    capsule_group = "vol-bright-bat"
    show_label = false

    [widget.screen_recorder]
    script = "scripts/screen_recorder.lua"
    type = "scripted"

[hooks]
battery_low_percent_threshold = 20
