title	Arch Linux (linux-cachyos)
linux	/vmlinuz-linux-cachyos
initrd	/intel-ucode.img
initrd	/initramfs-linux-cachyos.img
options root=LABEL=root zswap.enabled=1 zswap.compressor=zstd zswap.zpool=zsmalloc zswap.max_pool_percent=40 zswap.accept_threshold_percent=90 zswap.shrinker_enabled=1 rootflags=subvol=@ rw rootfstype=btrfs
