---
# roles/system/handlers/main.yml

- name: Re-sync pacman databases
  community.general.pacman:
    update_cache: true
  become: true

- name: Reload udev rules
  ansible.builtin.command: >
    udevadm control --reload-rules && udevadm trigger
  become: true
  changed_when: true
