[config]

[templates]
[templates.discord]
input_path = '~/.config/matugen/vesktop.css'
output_path = '~/.config/Vencord/themes/midnight-discord.css'

[templates.spicetify]
input_path = '~/.config/matugen/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'

[templates.zathura]
input_path = '~/.config/matugen/zathura-colors'
output_path = '~/.config/zathura/zathurarc'
