---
# roles/services/tasks/main.yml

- name: Enable systemd units
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
  loop: "{{ systemd_services }}"
  become: true

- name: Disable overridden systemd units
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    daemon_reload: false
  loop: "{{ systemd_services_disabled }}"
  become: true
